# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

parameters:
  - name: secretvalue
    type: string
    displayName: Enter secret value
    

steps:
  - task: AzureKeyVault@2
    inputs:
      azureSubscription: 'svc'
      KeyVaultName: 'keyvaultsh3351'
      SecretsFilter: '*'
      RunAsPreJob: false
    
  - task: CmdLine@2
    inputs:
      script: 'echo $(test-secret) > secret.txt'
      failOnStderr: 
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'svc'
      scriptType: 'ps'
      scriptLocation: 'inlineScript'
      inlineScript: 'az login'
  
  
    
